// players.js
export const players = [

    {
        old_number: 8.5,
        number: 8,
        name: "Isaac Araki",
        team: "Unknown",
        position: "Big",
        height: "6'3\"",
        weight: "220lbs",
        age: 21,
        season: 3,
        image: "images/isaac.png", 
        description: "<b>A raw, floor-stretching big with boundless hustle</b>, still finding his footing and defensive identity.",
        icons: ["Spacer", "Ridiculous Upside"],
        shades_of: ["Karl-Anthony Towns", "Mo Bamba"],
        offense: 0.2,
        defense: 0.55,
        aggressive: 0.35,
        stats: {
            shooting2: 0.2,
            shooting3: 0.2,
            playmaking: 0.2,
            perimeterDefense: 0.55,
            interiorDefense: 0.55,
            rebounding: 0.47
        },
    },
    {
        number: 1,
        name: "Paul Rosiak",
        team: "Golden State Warriors",
        position: "Forward",
        height: "6'0\"",
        weight: "175 lbs",
        age: 32,
        season: 3,
        image: "images/paul.png", 
        description: "<b>An on-ball menace with elite instincts</b>, paired with smooth offense that prizes efficiency over flair.",
        icons: ["Positional Versatility", "Finisher", "On-Ball Defense", "Injury Concerns"],
        shades_of: ["Dyson Daniels", "Trey Murphy"],
        offense: 0.85,
        defense: 0.9,
        aggressive: 0.25,
        stats: {
            shooting2: 0.85,
            shooting3: 0.85,
            playmaking: 0.85,
            perimeterDefense: 0.9,
            interiorDefense: 0.9,
            rebounding: 0.64
        },
    },
    {
        number: 2.9,
        name: "Mingma Sherpa",
        team: "Los Angeles Lakers",
        position: "Forward",
        height: "5'9\"",
        weight: "180 lbs",
        age: 24,
        season: 4,
        image: "images/ming.png", 
        description: "<b>Elite rebounder</b> with a knack for bold, clever passes that keep defenses guessing -- and fellow teammates too.",
        icons: ["Rebounding", "Clutch Gene", "Passing Virtuoso", "Feel For the Game" ],
        shades_of: ["Josh Hart", "Scottie Barnes"],
        offense: 0.55,
        defense: 0.65,
        aggressive: 0.5,
        stats: {
            shooting2: 0.55,
            shooting3: 0.55,
            playmaking: 0.55,
            perimeterDefense: 0.65,
            interiorDefense: 0.65,
            rebounding: 0.59
        },
    },
    {
        number: 2.99,
        name: "Lance Muchina",
        team: "Los Angeles Lakers",
        position: "Guard",
        height: "5'5\"",
        weight: "150 lbs",
        age: 24,
        season: 4,
        image: "images/lance.png", 
        description: "<b>Relentless on-ball defender</b> a consistent offense away from superstardom.",
        icons: ["On-Ball Defense", "Hustle", "Off-Ball Defense", "Got That Dog in Him"],
        shades_of: ["Dennis Schroeder", "Gary Payton II","Jose Alvarado", ],
        offense: 0.45,
        defense: 0.8,
        aggressive: 0.6,
        stats: {
            shooting2: 0.45,
            shooting3: 0.45,
            playmaking: 0.45,
            perimeterDefense: 0.8,
            interiorDefense: 0.8,
            rebounding: 0.72
        },
    },
    {
        number: 2,
        name: "Gavin Pereira",
        team: "Golden State Warriors",
        position: "Guard",
        height: "6'2\"",
        weight: "175 lbs",
        age: 24,
        season: "4 (Retired)",
        image: "images/gavin.png", 
        description: "<b>Crafty playmaker</b> sporting a silky crossover, with a knack for defending the perimeter.",
        icons: ["Passing Virtuoso", "Ballhandling", "Shot Blocking", "Pull-Up Threat"],
        shades_of: ["Kevin Durant"],
        offense: 0.8,
        defense: 0.65,
        aggressive: 0.6,
        stats: {
            shooting2: 0.8,
            shooting3: 0.8,
            playmaking: 0.8,
            perimeterDefense: 0.65,
            interiorDefense: 0.65,
            rebounding: 0.63
        }
    },
    {
        number: 3.0,
        name: "Declan Edgecombe",
        team: "Golden State Warriors",
        position: "Guard",
        height: "5'9\"",
        weight: "150 lbs",
        age: 25,
        season: 5,
        image: "images/declan.png", 
        description: "<b>High-energy point guard</b> who thrives on speed, constant movement, and creative shot-making.",
        icons: ["Lightning Rod", "Speed Demon", "Fast and Loose", "Floor General"],
        shades_of: ["Trae Young", "Tyus Jones"],
        offense: 0.7,
        defense: 0.6,
        aggressive: 0.6,
        stats: {
            shooting2: 0.7,
            shooting3: 0.7,
            playmaking: 0.7,
            perimeterDefense: 0.6,
            interiorDefense: 0.6,
            rebounding: 0.6
        }
    },

    {
        number: 8.4,
        name: "Byron Shirley",
        team: "LA Clippers",
        position: "Forward",
        height: "5'10\"",
        weight: "180 lbs",
        age: 40,
        season: 3,
        image: "images/byron.png", 
        description: "<b>Ageless hustle machine</b> defying father time with relentless effort, scrappy defense, and fearless dives.",
        icons: ["Hustle", "Ridiculous Upside", "Injury Concerns", "Sh*t Stirrer"],
        shades_of: ["Killian Hayes", "Udonis Haslem",],
        offense: 0.15,
        defense: 0.6,
        aggressive: 0.95,
        stats: {
            shooting2: 0.15,
            shooting3: 0.15,
            playmaking: 0.15,
            perimeterDefense: 0.6,
            interiorDefense: 0.6,
            rebounding: 0.74
        }
    },

    {
        number: 0,
        old_number: 1.5, 
        name: "Elliot Rosenberg",
        team: "Los Angeles Lakers", 
        position: "Forward",
        height: "5'11\"",
        weight: "190 lbs",
        age: 33,
        season: 3,
        image: "images/elliot.png", 
        description: "<b>High-usage scorer</b> whose strength and deliberate pace enable a versatile scoring package.",
        icons: ["Pull-up Threat", "Off-Ball Defense", "Post Moves", "Got That Dog In Him"],
        shades_of: ["Julius Randle", "LeBron James",],
        offense: 0.85,
        defense: 0.75,
        aggressive: 0.95,
        stats: {
            shooting2: 0.85,
            shooting3: 0.85,
            playmaking: 0.85,
            perimeterDefense: 0.75,
            interiorDefense: 0.75,
            rebounding: 0.83
        }
    },

    {
        number: 7.01,
        name: "Robby",
        team: "Los Angeles Lakers",
        position: "Big",
        height: "5'10\"",
        weight: "190 lbs",
        age: 31,
        season: 2,
        image: "images/robby.png", 
        description: "<b>An old-school center</b> whose strength and spacing make up for a lack of size.",
        icons: ["Spacer", "Shot Blocking"],
        shades_of: ["Chuck Hayes", "Kevon Looney"],
        offense: 0.4,
        defense: 0.6,
        aggressive: 0.2,
        stats: {
            shooting2: 0.4,
            shooting3: 0.4,
            playmaking: 0.4,
            perimeterDefense: 0.6,
            interiorDefense: 0.6,
            rebounding: 0.44
        }
    },

    {
        number: 2.71,
        name: "Victor Hyunh",
        team: "Los Angeles Lakers",
        position: "Guard",
        height: "5'10\"",
        weight: "170 lbs",
        age: 28,
        season: 5,
        image: "images/victor.png", 
        description: "<b>Fierce competitor</b> who excels at creating his own shot off-the-dribble.",
        icons: ["Pull-up Threat", "Clutch Gene", "Float Game", "Got That Dog in Him"],
        shades_of: ["Tyler Herro", "Kobe Bryant", ],
        offense: 0.8,
        defense: 0.4,
        aggressive: 0.8,
        stats: {
            shooting2: 0.8,
            shooting3: 0.8,
            playmaking: 0.8,
            perimeterDefense: 0.4,
            interiorDefense: 0.4,
            rebounding: 0.56
        }
    },

    {
        number: 1.91,
        old_number: 1.6,
        name: "Tyler Baldwin",
        team: "San Antonio Spurs",
        position: "Forward",
        height: "5'10\"",
        weight: "185 lbs",
        age: 22,
        season: 3,
        image: "images/tyler.png", 
        description: "<b>The prototypical modern power forward</b>, blending perimeter-stifling lateral quickness and strength with a dependable stroke from deep.",
        icons: ["On-Ball Defense", "Positional Versatility", "Spacer", "Hustle"],
        shades_of: ["OG Anunoby", "Kawhi Leonard", "Miles Bridges", "Aaron Gordon"],
        offense: 0.75,
        defense: 0.85,
        aggressive: 0.4,
        stats: {
            shooting2: 0.75,
            shooting3: 0.75,
            playmaking: 0.75,
            perimeterDefense: 0.85,
            interiorDefense: 0.85,
            rebounding: 0.67
        }
    },

    {
        number: 3,
        name: "Kevin Zhou",
        team: "Golden State Warriors",
        position: "Forward",
        height: "6'0\"",
        weight: "175 lbs",
        age: 31,
        season: 4,
        image: "images/kevinjr.png", 
        description: "<b>Unpredictable, athletic spark plug</b> whose shooting streaks can ignite a team.",
        icons: ["Athleticism", "Pull-up Threat", "Spacer", "Lightning Rod"],
        shades_of: ["Michael Porter Jr.", "Klay Thompson"],
        offense: 0.7,
        defense: 0.55,
        aggressive: 0.85,
        stats: {
            shooting2: 0.7,
            shooting3: 0.7,
            playmaking: 0.7,
            perimeterDefense: 0.55,
            interiorDefense: 0.55,
            rebounding: 0.67
        }
    },

    {
        number: 1.9,
        name: "Jason Roberts",
        team: "Golden State Warriors",
        position: "Forward",
        height: "5'7\"",
        weight: "165 lbs",
        age: 26,
        season: 3,
        image: "images/jason.png", 
        description: "<b>Jack-of-all-trades</b> guard who attacks the rim at will and can lock your favorite player up.",  // on a meteoric rise
        icons: ["On-Ball Defense", "Finisher", "Hustle", "Speed Demon"],
        shades_of: ["T.J. McConnell", "Alex Caruso"],
        offense: 0.8,
        defense: 0.85,
        aggressive: 0.85,
        stats: {
            shooting2: 0.8,
            shooting3: 0.8,
            playmaking: 0.8,
            perimeterDefense: 0.85,
            interiorDefense: 0.85,
            rebounding: 0.85
        }
    },
    {
        number: 7,
        name: "Logan Mar",
        team: "Boston Celtics",
        position: "Guard",
        height: "5'7\"",
        weight: "165 lbs",
        age: 23,
        season: 3,
        image: "images/logan.png", 
        description: "<b>Silent scoring option</b> with an arsenal of moves.",
        icons: ["Spacer", "Float Game"],
        shades_of: ["Kyle Anderson"],
        offense: 0.65,
        defense: 0.2,
        aggressive: 0.1,
        stats: {
            shooting2: 0.65,
            shooting3: 0.65,
            playmaking: 0.65,
            perimeterDefense: 0.2,
            interiorDefense: 0.2,
            rebounding: 0.16
        }
    },

    {
        number: 1000,
        name: "Chris White",
        team: "Washington Wizards",
        position: "Guard",
        height: "5'9\"",
        weight: "200 lbs",
        age: 25,
        season: "2 (Retired)",
        image: "images/chris.png", 
        description: "<b>Unpredictable loose cannon</b> whose creativity hurts as much as it helps.",
        icons: ["Fast and Loose", "Human Highlight"],
        shades_of: ["Kevin Porter Jr."],
        offense: 0.15,
        defense: 0.4,
        aggressive: 0.95,
        stats: {
            shooting2: 0.15,
            shooting3: 0.15,
            playmaking: 0.15,
            perimeterDefense: 0.4,
            interiorDefense: 0.4,
            rebounding: 0.62
        }
    },
    {
        number: 6.9,
        name: "Justine",
        team: "Los Angeles Lakers",
        position: "Guard",
        height: "5'9\"",
        weight: "190 lbs",
        age: 28,
        season: "2",
        image: "images/justine.png", 
        description: "<b>Offensive talent</b> with the size to take it inside and the skill to shoot from way outside.",
        icons: ["Ballhandling", "Pull-up Threat", "Spacer", "Finisher"],
        shades_of: ["David Roddy"],
        offense: 0.6,
        defense: 0.5,
        aggressive: 0.45,
        stats: {
            shooting2: 0.6,
            shooting3: 0.6,
            playmaking: 0.6,
            perimeterDefense: 0.5,
            interiorDefense: 0.5,
            rebounding: 0.48
        }
    },
    {
        number: 2.8999,
        name: "Allen",
        team: "Unknown",
        position: "Center",
        height: "6'0\"",
        weight: "220 lbs",
        age: 27,
        season: "2",
        image: "images/allen.png", 
        description: "<b>Relentless enforcer</b> with elite help instincts and a smooth touch to match his grit.",
        icons: ["Shot Blocking", "Off-Ball Defense", "Sh*t Stirrer", "Ridiculous Upside"],
        shades_of: ["Brook Lopez", 'Myles Turner'],
        offense: 0.6,
        defense: 0.75,
        aggressive: 0.4,
        stats: {
            shooting2: 0.6,
            shooting3: 0.6,
            playmaking: 0.6,
            perimeterDefense: 0.75,
            interiorDefense: 0.75,
            rebounding: 0.61
        }
    },
    {
        number: 2.6,
        name: "Josh Lee",
        team: "Washington Wizards",
        position: "Guard",
        height: "5'7\"",
        weight: "155 lbs",
        age: 25,
        season: "4",
        image: "images/josh.png", 
        description: "<b>Blistering guard</b> who thrives in transition and punishes defenses from deep.",
        icons: ["Speed Demon", "Pull-up Threat", "Fast and Loose", "Human Highlight"],
        shades_of: ["Tyrese Maxey", "Immanuel Quickley"],
        offense: 0.8,
        defense: 0.45,
        aggressive: 0.85,
        stats: {
            shooting2: 0.8,
            shooting3: 0.8,
            playmaking: 0.8,
            perimeterDefense: 0.45,
            interiorDefense: 0.45,
            rebounding: 0.61
        }
    },
    {
        number: 6.91,
        name: "Anup Rao",
        team: "Unknown",
        position: "Guard",
        height: "5'9\"",
        weight: "155 lbs",
        age: 43,
        season: "2",
        image: "images/anup.png", 
        description: "<b>Confident shooter</b> whose endurance is unmatched.",
        icons: ["Pull-up Threat", "Spacer", "Movement Shooter"],
        shades_of: ["Kevin Huerter", "Joe Harris"],
        offense: 0.55,
        defense: 0.55,
        aggressive: 0.5,
        stats: {
            shooting2: 0.55,
            shooting3: 0.55,
            playmaking: 0.55,
            perimeterDefense: 0.55,
            interiorDefense: 0.55,
            rebounding: 0.53
        }
    },
    {
        number: 3.51,
        name: "Sean Ly",
        team: "Golden State Warriors",
        position: "Guard",
        height: "5'6\"",
        weight: "160 lbs",
        age: 29,
        season: "3",
        image: "images/sean.png", 
        description: "<b>Steady small guard</b> who quietly cashes in from mid-range and beyond.",
        icons: ["Spacer", "Feel For the Game"],
        shades_of: ["De'Anthony Melton"],
        offense: 0.65,
        defense: 0.4,
        aggressive: 0.3,
        stats: {
            shooting2: 0.65,
            shooting3: 0.65,
            playmaking: 0.65,
            perimeterDefense: 0.4,
            interiorDefense: 0.4,
            rebounding: 0.36
        }
    },
    {
        number: 8.5,
        name: "Daniel",
        team: "Unknown",
        position: "Guard",
        height: "5'9\"",
        weight: "160lbs",
        age: 23,
        season: "4 (Retired)",
        image: "images/daniel.png", 
        description: "<b>Decisive driver</b> still searching for a rhythm from beyond the arc.",
        icons: ["Fast and Loose", "Ridiculous Upside"],
        shades_of: ["Russell Westbrook"],
        offense: 0.3,
        defense: 0.3,
        aggressive: 0.75,
        stats: {
            shooting2: 0.3,
            shooting3: 0.3,
            playmaking: 0.3,
            perimeterDefense: 0.3,
            interiorDefense: 0.3,
            rebounding: 0.48
        }
    },
    {
        number: 1.1,
        name: "Alexis Dominguez",
        team: "Unknown",
        position: "Guard",
        height: "5'11\"",
        weight: "170lbs",
        age: 25,
        season: "4 (Retired)",
        image: "images/alexis.png", 
        description: "<b>A highly coveted two-way wing</b>, equally gifted at playmaking on offense and on defense.",
        icons: ["Pull-up Threat", "Passing Virtuoso", "Positional Versatility", "On-Ball Defense"],
        shades_of: ["Paul George", "D'Angelo Russell"],
        offense: 0.9,
        defense: 0.8,
        aggressive: 0.5,
        stats: {
            shooting2: 0.9,
            shooting3: 0.9,
            playmaking: 0.9,
            perimeterDefense: 0.8,
            interiorDefense: 0.8,
            rebounding: 0.68
        }
    },

    {
        old_number: 3.01,
        number: 2.9,
        name: "Mo",
        team: "Unknown",
        position: "Guard",
        height: "5'10\"",
        weight: "170lbs",
        age: 23,
        season: "3 (Retired)",
        image: "images/mo.png", 
        description: "<b>Unabashed tough-shot maker</b> able to take over a game", // whether he's hot or not
        icons: ["Movement Shooter", "Pull-up Threat", "Spacer", "Fast and Loose"],
        shades_of: ["Norman Powell"],
        offense: 0.75,
        defense: 0.65,
        aggressive: 0.9,
        stats: {
            shooting2: 0.75,
            shooting3: 0.75,
            playmaking: 0.75,
            perimeterDefense: 0.65,
            interiorDefense: 0.65,
            rebounding: 0.75
        }
    },

    {
        number: 2.86,
        name: "Minghui \"Lu\"",
        team: "Rockets",
        position: "Center",
        height: "5'10\"",
        weight: "185 lbs",
        age: 32,
        season: "5 (Semi-Retired)",
        image: "images/lu.png", 
        description: "<b>Creative offensive playmaker</b> who dominates the post with savvy veteran moves.", // whether he's hot or not
        icons: ["Post Moves", "Passing Virtuoso", "Feel For the Game", "Floor General"],
        shades_of: ["Alperen Sengun", "Nikola Jokic", "Domantis Sabonis"],
        offense: 0.75,
        defense: 0.5,
        aggressive: 0.75,
        stats: {
            shooting2: 0.75,
            shooting3: 0.75,
            playmaking: 0.75,
            perimeterDefense: 0.5,
            interiorDefense: 0.5,
            rebounding: 0.6
        }
    },

    {
        number: 2.85,
        name: "Kevin Ly",
        team: "Unknown",
        position: "Guard",
        height: "5'8\"",
        weight: "185 lbs",
        age: 32,
        season: "5 (Retired)",
        image: "images/ogkevin.png", 
        description: "<b>An almost unfathomably accurate shooter</b>, making him an unquestionably valuable addition for any team.",
        icons: ["Clutch Gene", "Spacer", "Feel For the Game"],
        shades_of: ["Eric Gordon",],
        offense: 0.75,
        defense: 0.6,
        aggressive: 0.25,
        stats: {
            shooting2: 0.75,
            shooting3: 0.75,
            playmaking: 0.75,
            perimeterDefense: 0.6,
            interiorDefense: 0.6,
            rebounding: 0.46
        }
    },
    {
        number: 2.5999,
        name: "Mitch Ly",
        team: "Golden State Warriors",
        position: "Guard",
        height: "5'8\"",
        weight: "170 lbs",
        age: 22,
        season: "2 (Retired)",
        image: "images/mitch.png", 
        description: "<b>A dynamic sharpshooter</b> with slick footwork and crafty finishes at the rim—when his shoulder lets him play. ",
        icons: ["Ballhandling", "Pull-up Threat", "Finisher",  "Injury Concerns"],
        shades_of: ["Ty Jerome", "Payton Pritchard"],
        offense: 0.8,
        defense: 0.4,
        aggressive: 0.3,
        stats: {
            shooting2: 0.8,
            shooting3: 0.8,
            playmaking: 0.8,
            perimeterDefense: 0.4,
            interiorDefense: 0.4,
            rebounding: 0.36
        }
    },
    {
        number: 2.88,
        name: "Eric Pham",
        team: "Unknown",
        position: "Guard",
        height: "5'9\"",
        weight: "185 lbs",
        age: 21,
        season: "3",
        image: "images/eric.png", 
        description: "<b>Outspoken floor general</b> who leverages his muscle on both ends.",
        icons: ["Floor General", "Pull-up Threat", "Sh*t Stirrer", "Injury Concerns"],
        shades_of: ["Eric Bledsoe"],
        offense: 0.7,
        defense: 0.7,
        aggressive: 0.8,
        stats: {
            shooting2: 0.7,
            shooting3: 0.7,
            playmaking: 0.7,
            perimeterDefense: 0.7,
            interiorDefense: 0.7,
            rebounding: 0.74
        }
    },
    {
        number: 7.01,
        old_number: 6.911,
        name: "Phil",
        team: "Unknown",
        position: "Guard",
        height: "6'1\"",
        weight: "175 lbs",
        age: 60,
        season: "Unknown",
        image: "images/phil.png", 
        description: "<b>Veteran sharpshooter</b> who haunts the perimeter, but is too often a ghost on defense.",
        icons: ["Pull-up Threat", "Spacer", "Artist"],
        shades_of: [""],
        offense: 0.65,
        defense: 0.25,
        aggressive: 0.75,
        stats: {
            shooting2: 0.65,
            shooting3: 0.65,
            playmaking: 0.65,
            perimeterDefense: 0.25,
            interiorDefense: 0.25,
            rebounding: 0.45
        }
    },
    {
        number: 1.999,
        name: "Lorne (Loren?)",
        team: "Unknown",
        position: "Guard",
        height: "5'10\"",
        weight: "160 lbs",
        age: 50,
        season: "Unknown",
        image: "images/lorne.png", 
        description: "<b>Unlikely scoring savant</b> equipped with surprising athleticism and timely outside shooting.",
        icons: ["Pull-up Threat", "Feel For the Game", "Clutch Gene", "Movement Shooter"],
        shades_of: ["Stephen Curry"],
        offense: 0.85,
        defense: 0.6,
        aggressive: 0.5,
        stats: {
            shooting2: 0.85,
            shooting3: 0.85,
            playmaking: 0.85,
            perimeterDefense: 0.6,
            interiorDefense: 0.6,
            rebounding: 0.56
        }
    },
    {
        number: 3.51,
        name: "Steve",
        team: "Unknown",
        position: "Center",
        height: "6'2\"",
        weight: "190 lbs",
        age: 50,
        season: "Unknown",
        image: "images/steve.png", 
        description: "<b>Bruising backdown punisher</b> who also makes the right reads in the two-man game.",
        icons: ["Post Moves", "Shot Blocking"],
        shades_of: ["Bobby Portis", "Aaron Gordon"],
        offense: 0.7,
        defense: 0.65,
        aggressive: 0.65,
        stats: {
            shooting2: 0.7,
            shooting3: 0.7,
            playmaking: 0.7,
            perimeterDefense: 0.65,
            interiorDefense: 0.65,
            rebounding: 0.65
        }
    },

    {
        number: 2.65,
        name: "Skyler Hallinan",
        team: "LA Clippers",
        position: "Wing",
        height: "5'11\"",
        weight: "160 lbs",
        age: 24,
        season: "6",
        image: "images/skyler.png", 
        description: "<b>Veteran sharpshooter whose athletic finishes and foul-baiting tactics are perpetually threatened by nagging injuries.</b>",
        icons: ["Spacer", "Injury Concerns"],
        shades_of: ["Mikal Bridges"],
        offense: 0.7,
        defense: 0.7,
        aggressive: 0.6,
        stats: {
            shooting2: 0.7,
            shooting3: 0.7,
            playmaking: 0.7,
            perimeterDefense: 0.7,
            interiorDefense: 0.7,
            rebounding: 0.66
        }
    },
    // {
    //     number: 8.6,
    //     name: "Leonard",
    //     team: "Unknown",
    //     position: "Guard",
    //     height: "5'10\"",
    //     weight: "180 lbs",
    //     age: 55,
    //     season: "Unknown",
    //     image: "images/leonard.png", 
    //     description: "",
    //     icons: [""],
    //     shades_of: []
    // },
    // {
    //     number: 6.9101,
    //     name: "Anish",
    //     team: "Unknown",
    //     position: "Guard",
    //     height: "5'9\"",
    //     weight: "175 lbs",
    //     age: 21,
    //     season: "Unknown",
    //     image: "images/anish.png", 
    //     description: "",
    //     icons: [""],
    //     shades_of: []
    // },
];